# Generated by Django 3.0.3 on 2020-03-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_ui', '0007_multiuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.TextField()),
                ('correct', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='./web_ui/static/img/uploads', verbose_name='img')),
                ('caption', models.TextField()),
                ('options', models.ManyToManyField(to='web_ui.Option')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(max_length=250)),
                ('questions', models.ManyToManyField(to='web_ui.Question')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
