# Generated by Django 3.0.3 on 2020-03-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_ui', '0008_auto_20200312_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='./web_ui/static/img/uploads', verbose_name='img')),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.TextField(),
        ),
    ]
