# Generated by Django 3.0.3 on 2020-03-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_ui', '0009_auto_20200312_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
