# Generated by Django 3.0.3 on 2020-03-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_ui', '0012_auto_20200313_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiuser',
            name='quiz_completed',
            field=models.ManyToManyField(blank=True, to='web_ui.QuizCompleted'),
        ),
    ]
