# Generated by Django 3.0.3 on 2020-03-13 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_ui', '0013_auto_20200313_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizcompleted',
            name='correct',
        ),
        migrations.RemoveField(
            model_name='quizcompleted',
            name='option_selected',
        ),
        migrations.CreateModel(
            name='QuestionsCompleted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options_selected', models.TextField()),
                ('correct', models.BooleanField()),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web_ui.Question')),
            ],
        ),
        migrations.AddField(
            model_name='quizcompleted',
            name='questions_completed',
            field=models.ManyToManyField(blank=True, to='web_ui.QuestionsCompleted'),
        ),
    ]
