# Generated by Django 3.0.3 on 2020-03-13 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_ui', '0015_auto_20200313_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionscompleted',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_ui.Question'),
        ),
    ]
